import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Merriweather } from "next/font/google";
import localFont from "next/font/local";
import { GooeyToaster } from "@/components/ui/goey-toaster";
import "../styles/globals.css";
import "goey-toast/styles.css";
import { cn } from "@/lib/utils";

const merriweatherHeading = Merriweather({
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const advercase = localFont({
  src: [
    { path: "../assets/fonts/Advercase-Regular.woff2", weight: "400" },
    { path: "../assets/fonts/Advercase-Bold.woff2", weight: "700" },
  ],
  variable: "--font-advercase",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased font-sans",
        geistSans.variable,
        geistMono.variable,
        inter.variable,
        merriweatherHeading.variable,
        advercase.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <GooeyToaster position="top-center" showProgress closeButton="top-right" />
      </body>
    </html>
  );
}
