import type { Metadata } from "next";
import type { ReactNode } from "react";
// import NoiseOverlay from "@/components/background/NoiseOverlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      {children}
      {/* <NoiseOverlay /> */}
    </>
  );
}
